spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hnp_db
    username: root
    password: x1m1hck2
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: USER-SERVICE