spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zenzone_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

  application:
    name: ZenZone
