spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zenzone_db
    username: root
    password: 173314
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: ZenZone